  
# Adapted from spdlog: https://github.com/gabime/spdlog
sudo: required
language: cpp

# gcc 4.8
addons: &gcc48
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

# gcc 7.0
addons: &gcc7
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

# gcc 9.0
addons: &gcc9
  apt:
    packages:
      - g++-9
    sources:
      - ubuntu-toolchain-r-test

# Clang 3.6
addons: &clang36
  apt:
    packages:
      - clang-3.6
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      
# Clang 10.0
addons: &clang10
  apt:
    packages:
      - clang-10
      - lldb-10
      - lld-10
    sources:
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"


matrix:
  include:
    # Test gcc-4.8: Build=Debug/Release
    - env: GCC_VERSION=4.8 BUILD_TYPE=Debug
      os: linux
      addons: *gcc48

    - env: GCC_VERSION=4.8 BUILD_TYPE=Release
      os: linux
      addons: *gcc48

    # Test gcc-7.0: Build=Debug/Release
    - env: GCC_VERSION=7 BUILD_TYPE=Debug
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=7 BUILD_TYPE=Release
      os: linux
      addons: *gcc7

    # Test gcc-9.0: Build=Debug/Release
    - env: GCC_VERSION=9 BUILD_TYPE=Debug
      os: linux
      addons: *gcc9

    - env: GCC_VERSION=9 BUILD_TYPE=Release
      os: linux
      addons: *gcc9

    # Test clang-3.6: Build=Debug/Release
    - env: CLANG_VERSION=3.6 BUILD_TYPE=Debug
      os: linux
      addons: *clang36

    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release
      os: linux
      addons: *clang36

    # Test clang-10.0: Build=Debug/Release
    - env: CLANG_VERSION=10 BUILD_TYPE=Debug
      os: linux
      dist: bionic
      addons: *clang10

    - env: CLANG_VERSION=10 BUILD_TYPE=Release
      os: linux
      dist: bionic
      addons: *clang10

    # osx: Build=Debug/Release
    - env: BUILD_TYPE=Debug
      os: osx

    - env: BUILD_TYPE=Release
      os: osx

    # Windows
    - env: BUILD_TYPE=Debug
      os: windows

    - env: BUILD_TYPE=Release
      os: windows


before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbuild/$BUILD_TYPE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build build/$BUILD_TYPE --config $BUILD_TYPE
  - cd build/$BUILD_TYPE
  - ctest -j2 --output-on-failure